# Este archivo va a declarar como y desde donde se va a iniciar
# este contenedor

services:
  app-csv:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    

# Se lee como: "Vas a construir este servicio desde la carpeta
# en la que estoy ubicado y en esa carpeta que estás ubicado vas
# a buscar el archivo Dockerfile"
